name: fire-detection
channels:
  - pytorch
  - conda-forge
  - defaults

dependencies:
  # Python
  - python=3.9

  # PyTorch and related
  - pytorch>=1.12.0
  - torchvision>=0.13.0
  - torchaudio>=0.12.0
  - cudatoolkit=11.6  # For CUDA support (adjust version as needed)

  # Core scientific computing
  - numpy>=1.21.0
  - scipy>=1.7.0
  - scikit-learn>=1.0.0

  # Image processing
  - pillow>=8.3.0
  - opencv>=4.5.0

  # Data visualization
  - matplotlib>=3.5.0
  - seaborn>=0.11.0
  - plotly>=5.0.0

  # Jupyter and notebook support
  - jupyter>=1.0.0
  - jupyterlab>=3.0.0
  - ipykernel>=6.0.0
  - ipywidgets>=7.6.0

  # Progress bars and utilities
  - tqdm>=4.60.0

  # File handling
  - glob2>=0.7

  # Additional utilities
  - pandas>=1.3.0  # For data manipulation if needed
  - pyyaml>=5.4.0  # For configuration files

  # Development tools (optional)
  - black>=21.0.0  # Code formatting
  - flake8>=3.9.0  # Linting

  # Pip packages (if not available via conda)
  - pip
  - pip:
    - tensorboard>=2.8.0  # For training visualization
    - albumentations>=1.1.0  # Advanced image augmentations (optional)

# Optional: specify prefix for environment location
# prefix: /path/to/envs/fire-detection